raft:
  tick_millis_duration: 3000
  leader_seen_timeout: 5
  candidate_election_timeout: 5
  candidate_election_timeout_rand: 6
  leader_idle_timeout: 4
storage:
  max_memtable_size: 24
  data_path: "./db-data"

