server:
  raft_port: 8080
  outbound_port: 5000
raft:
  tick_millis_duration: 150
  leader_seen_timeout: 5
  candidate_election_timeout: 5
  candidate_election_timeout_rand: 6
  leader_idle_timeout: 4
storage:
  max_memtable_size: 262144
  data_path: "./db-data"
