version: "3.8"

services:
  peer1:
    build:
      context: .
    environment:
      - PEER_ADDR=192.30.0.101:8080
      - PEERS=192.30.0.102:8080, 192.30.0.103:8080
    networks:
      raft_network:
        ipv4_address: 192.30.0.101
    ports:
      - "8081:8080"

  peer2:
    build:
      context: .
    environment:
      - PEER_ADDR=192.30.0.102:8080
      - PEERS=192.30.0.101:8080, 192.30.0.103:8080
    networks:
      raft_network:
        ipv4_address: 192.30.0.102
    ports:
      - "8082:8080"

  peer3:
    build:
      context: .
    environment:
      - PEER_ADDR=192.30.0.103:8080
      - PEERS=192.30.0.101:8080, 192.30.0.102:8080
    networks:
      raft_network:
        ipv4_address: 192.30.0.103
    ports:
      - "8083:8080"

networks:
  raft_network:
    name: raft_network
    ipam:
      driver: default
      config:
        - subnet: 192.30.0.0/24
