services:
  peer1:
    image: alexandria-image
    build:
      context: .
    environment:
      - PEER_ADDR=192.30.0.101:8080
      - PEERS=192.30.0.102:8080,192.30.0.103:8080
    networks:
      raft_network:
        ipv4_address: 192.30.0.101
    ports:
      - "8081:8080"
    volumes:
      - ./logs/peer1/:/usr/src/raft/logs/

  peer2:
    image: alexandria-image
    environment:
      - PEER_ADDR=192.30.0.102:8080
      - PEERS=192.30.0.101:8080,192.30.0.103:8080
    networks:
      raft_network:
        ipv4_address: 192.30.0.102
    ports:
      - "8082:8080"
    volumes:
      - ./logs/peer2/:/usr/src/raft/logs/

  peer3:
    image: alexandria-image
    environment:
      - PEER_ADDR=192.30.0.103:8080
      - PEERS=192.30.0.101:8080,192.30.0.102:8080
    networks:
      raft_network:
        ipv4_address: 192.30.0.103
    ports:
      - "8083:8080"
    volumes:
      - ./logs/peer3/:/usr/src/raft/logs/

networks:
  raft_network:
    name: raft_network
    ipam:
      driver: default
      config:
        - subnet: 192.30.0.0/24
