version: "3.8"
services:
  peer1:
    build:
      context: .
    environment:
      - PEER_ADDR=127.0.0.1:8080
      - PEERS=127.0.0.1:8081
    ports:
      - "8080:8080"
  peer2:
    build:
      context: .
    environment:
      - PEER_ADDR=127.0.0.1:8081
      - PEERS=127.0.0.1:8080
    ports:
      - "8081:8081"
